services:
  your-letterboxd:
    build: .
    container_name: your-letterboxd
    ports:
      - "60007:8000"
    volumes:
      - ./data:/app/data
    environment:
      - LETTERBOXD_USERNAME=${LETTERBOXD_USERNAME}
      - TMDB_ACCESS_TOKEN=${TMDB_ACCESS_TOKEN}
      - DATABASE_PATH=/app/data/letterboxd.db
      - SYNC_SCHEDULE=30 16 * * *
      - SYNC_MIN_DELAY=4.0
      - TMDB_MIN_DELAY=0.3
    restart: unless-stopped
